insert into book(title, author, year) VALUES ('The Shawshank redemption', 'Stephen King', 1982),
                                             ('Flowers for Algernon', 'Daniel Keyes', 1959),
                                             ('The Godfather', 'Mario Puzo', 1969),
                                             ('Gone with the wind', 'Margaret Mitchell', 1936),
                                             ('The green mile', 'Stephen Kingг', 1996),
                                             ('Harry Potter and the prisoner of Azkaban', 'Joanne Rowling', 1999),
                                             ('The Master and Margarita', 'Mikhail Bulgakov', 1940),
                                             ('Crime and punishment', 'Fyodor Dostoevsky', 1866),
                                             ('A Hhro of our time', 'Mikhail Lermontov', 1840),
                                             ('The Diary', 'Anne Frank', 1947),
                                             ('The Critique of Pure Reason', 'Immanuel Kant', 1781),
                                             ('The Sovereign', 'Niccolo Machiavelli', 1532),
                                             ('On the origin of Species', 'Charles Darwin', 1859),
                                             ('Das Kapital', 'Carl Marx', 1867),
                                             ('Leviathan', 'Thomas Hobbes', 1651);

insert into person(name, birth) VALUES ('Joel Sharp', 1985),
                                       ('Bailey Armstrong', 1970),
                                       ('Fletcher Pickett', 1988),
                                       ('Juelz Crane', 1957),
                                       ('Hayden Murray', 1994),
                                       ('Toby Harrison', 1940),
                                       ('Journey Ellison', 2004)